name: CommandSurplus
version: 1.0
author: DavidoTek
main: net.davidotek.CommandSurplus.CommandSurplus
commands:
  commandsurplus:
    description: CommandSurplus main command
    usage: /commandsurplus <action> <command> [<value>]